[package]
name = "usi_play_match"
version = "0.2.1"
authors = ["HiraokaTakuya <hiraoka64@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
structopt = "0.2.15"
tokio = { version = "0.2", features = ["full"] }
